### ISSUE TITLE
iphone , 支付宝内置浏览器 亲测不能复制 老铁,盘他

### ISSUE THREAD

**Issue by higsx** [majiang666/copy#3]

**Comment by majiang666** [comment]
谢谢反馈，我用支付宝浏览器试过了，目前问题集中在ios9及以下对复制支持不太友好，目前的解决方案：  （手头没有可复现的设备，亲尝试以后反馈下，谢谢。）  

1：对于不支持的机型，可以友好的提示用户手动复制 

2：纯css方案解决

```
//长按复制内容一定要p标签
p的父元素{
    -webkit-user-select:text;
}
p{
    -webkit-user-select:text;
    -moz-user-select:text;
    -ms-user-select:text;
    user-select:text;
}
```

3：低版本改为长按复制   

```
-webkit-touch-callout: all;
-webkit-user-select: all;
-moz-user-select: all;
-ms-user-select: all;
user-select: all;
```

参考：  

https://blog.csdn.net/weixin_33730836/article/details/93176781  

https://blog.csdn.net/qq_40028324/article/details/89461265
